data<-read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
data$DateTime<-as.POSIXct(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
data$Date<-as.Date(data$Date, "%d/%m/%Y")
data2<-data[which(data$Date>=as.Date("2007-02-01") & data$Date<=as.Date("2007-02-02")),]
png(filename="plot3.png", width=480, height=480, units="px")
with(data2, plot(DateTime, Sub_metering_1, type="l", ylim=c(0, max(Sub_metering_1, Sub_metering_2, Sub_metering_3)), ylab="Energy sub metering", xlab=NA))
lines(data2$DateTime, data2$Sub_metering_2, type="l", col="red")
lines(data2$DateTime, data2$Sub_metering_3, type="l", col="blue")
legend("topright", pch="-", col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()